[package]
name = "rest"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web.workspace = true
serde.workspace = true
serde_json.workspace = true
sea-orm.workspace = true
sql-entities.workspace = true
chrono.workspace = true