[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { workspace = true }
actix-web.workspace = true
sql-entities.workspace = true
sea-orm = { workspace = true }